### ISSUE TITLE
path error - `run build` incomplete

### ISSUE THREAD

**Issue by jonkwheeler** [kbariotis/kostasbariotis.com#1]
Hey, I was following ago to your [blog post here](https://www.gatsbyjs.org/blog/2017-09-18-gatsby-modern-static-generation/) over at Gatsby.

Cloned your repo here, installed dependencies, ran `npm run develop` and then `npm run build` in a separate tab.

Here's the output in the terminal - 

```
Jons-MacBook-Pro:kostasbariotis.com jonwheeler$ npm run build

> kostasbariotis.com@ build /Users/jonwheeler/jon_code/kostasbariotis.com
> gatsby build

success delete html files from previous builds — 0.103 s
success open and validate gatsby-config.js — 0.011 s
success copy gatsby files — 0.028 s
success source and transform nodes — 0.167 s
success building schema — 0.440 s
success createLayouts — 0.012 s
success createPages — 0.507 s
success createPagesStatefully — 0.059 s
success extract queries from components — 0.221 s
success run graphql queries — 0.425 s
success write out page data — 0.013 s
success write out redirect data — 0.001 s
success update schema — 0.245 s

info bootstrap finished - 4.174 s
```

This all looks great. And the localhost looks great. However, when I open up `public/index.html`, your site has a path issue. 

For example, the header image is looking for `file:///static/header_index.1b64bb2b.jpg`. This applied to everything inside the `static/` folder, as well as js chunks. Everything wants to looks for `file://...`.

Also, the links to blog posts do not work. An example, your first post is `http://localhost:8000/modern-static-site-generation/` but the static site gen is returning`file:///modern-static-site-generation/`.

Anyways, I'm new to Gatsby, but I'm sure it's a quick path bug fix somewhere. I just wanted you to be aware. Cheers.

![screenshot 2017-09-21 11 58 04](https://user-images.githubusercontent.com/3136271/30706461-67255bb0-9ec6-11e7-9b5d-07ed631d8cc1.png)

**Comment by kbariotis** [comment]
@jonkwheeler you need an HTTP server to serve the `public` folder. Run `npm run serve` to start Gatsby's builtin server. 

😉

**Comment by jonkwheeler** [comment]
Oh god. This is me right now 🤦‍♂️ https://media1.giphy.com/media/XsUtdIeJ0MWMo/200w.gif

Alright. Follow up question. Do you know why the HTTP served site (which should be the static gen site, not React site) shows as running React? `This page is using the production build of React`. 

Edit: I guess I'm seeing other Gatsby examples as the same. I just figured if gatsby takes a react site and outputs static content, that the React Dev Tools wouldn't recognize it as a react site. Clearly I have that wrong.
