### ISSUE TITLE
Pagination: Empty /page/0, last page

### ISSUE THREAD

**Issue by fk** [kbariotis/kostasbariotis.com#2]
Hey @kbariotis! I stumbled upon your blog article and repo when googling for "gatsby pagination" today and wanted to say thanks for providing an example! 🤗 

Also I wanted to let you know that I found two small issues with your current implementation:

* A page without posts is created: https://kostasbariotis.com/page/0/.
* The last available page at https://kostasbariotis.com/page/13 says "Page 13 of 14".
* If I'm not completely mistaken, the last page of paginated posts (14) is never created. (Edit: Did a quick search in `src/pages` for `2013` and yep, seems like e.g. https://kostasbariotis.com/peges-empneuses-101/ should be on the missing page 14).

I think both should be easily fixed by slightly modifying https://github.com/kbariotis/kostasbariotis.com/blob/80cbbb50cb40ffa371befc29e91d89ce0d6dc28b/gatsby-node.js#L132
to `let page = 1; page <= pagesSum` – theoretically, haven't cloned/tested.

**Comment by kbariotis** [comment]
Indeed, there is an issue there @fk. Thank you so much, I will look at it soon.
