### ISSUE TITLE
Build error:  "Module build failed: SyntaxError: Unexpected token g in JSON at position 4212"

### ISSUE THREAD

**Issue by rdricco** [kbariotis/kostasbariotis.com#3]
I got this error when trying to build, everything looks fine when on develop mode.

> gatsby build
>
> success delete html files from previous builds — 0.034 s
> success open and validate gatsby-config.js — 0.007 s
> success copy gatsby files — 0.115 s
> success onPreBootstrap — 0.009 s
> success source and transform nodes — 0.389 s
> success building schema — 0.509 s
> success createLayouts — 0.014 s
> success createPages — 0.634 s
> success createPagesStatefully — 0.154 s
> success onPreExtractQueries — 0.001 s
> success extract queries from components — 0.369 s
> success run graphql queries — 0.927 s
> success write out page data — 0.028 s
> success write out redirect data — 0.003 s
> success update schema — 0.378 s
> success onPostBootstrap — 0.001 s
> 
> info bootstrap finished - 7.114 s
> 
> success Building CSS — 10.950 s
> success Building production JavaScript bundles — 21.368 s
> 
> error Building static HTML for pages failed
> 
> See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
> 
> 
>   Error: Module build failed: SyntaxError: Unexpected token g in JSON at position 42125
> 
>   - JSON.parse
> 
>   - index.js:4 Object.module.exports
>     [kostasbariotis.com]/[json-loader]/index.js:4:49
> 
>   - @ ./.cache/sync-requires.js 23:22-120 24:1005-1103

**Comment by kbariotis** [comment]
Thanks for filing this issue @rdricco. I have updated Gatsby and also made a slight change that I think was breaking due to a recent update of Gatsby (not sure though). It works now. Check it and let me know if something went wrong. 🙂

**Comment by rdricco** [comment]
Everything works fine now. Thanks.
