### ISSUE TITLE
Syntax error + unknown markdown

### ISSUE THREAD

**Issue by Cobwebster** [kbariotis/kostasbariotis.com#7]
Hey, I'm confused as to why this isn't working, it just doesn't render my pages. For starters the documents say use this import

import { paginate } from 'gatsby-awesome-pagination'; in the nodeJs file then when I do I get this error, 

` import { paginate } from 'gatsby-awesome-pagination';
         ^
  SyntaxError: Unexpected token {`

This is my exports in nodeJs

https://hastebin.com/qigexojeme.php

This is what I put in my component 

`
export const pageQuery = graphql``
  query ($skip: Int!, $limit: Int!) {
    allMarkdownRemark(
      sort: { fields: [frontmatter___date], order: DESC }
      skip: $skip 
      limit: $limit
    )
  }
`

which throws this error-

error GraphQL Error Encountered 1 error(s):
- Unknown field 'allMarkdownRemark' on type 'Query'.

https://hastebin.com/ojeduzaniv.xml

-- Seems like the documentation missed out important steps? Or did I just overlook something.

**Comment by kbariotis** [comment]
Hi @Cobwebster, I believe that you should open this issue in [this repo](https://github.com/GatsbyCentral/gatsby-plugin-awesome-pagination). My repo uses [this plugin](https://github.com/kbariotis/gatsby-plugin-paginate). Give that a try if you like and let me know how it goes. 👍

**Comment by Cobwebster** [comment]
> Hi @Cobwebster, I believe that you should open this issue in [this repo](https://github.com/GatsbyCentral/gatsby-plugin-awesome-pagination). My repo uses [this plugin](https://github.com/kbariotis/gatsby-plugin-paginate). Give that a try if you like and let me know how it goes. 👍

ah yeah, my bad :)
